### ISSUE TITLE
FOI: example of ephys timeseries view on remote data - colab notebook

### ISSUE THREAD

**Issue by magland** [spikodrome/administrative#2]
A prelim example of viewing a remote timeseries with lazy loading over network - on colab:

https://colab.research.google.com/drive/1gzYEdp_C3p6XTE8Q-pB48ZGv47cQB9DZ

However, does not yet use .nwb format. The purpose of the h5_to_json project is to support nwb format in this kind of situation. So there are just a couple things to connect together to make this work.

**Comment by yarikoptic** [comment]
I forgot to check collab, may be it somehow has such a magical feature - is it possible to parametrize notebook, so url to it's invocation would provide URL to the file to analyze (instead of needing to enter it in a cell within notebook)?

**Comment by magland** [comment]
Unfortunately, colab cannot be used in that way -- I've tried to think of how but came up short.

**Comment by yarikoptic** [comment]
Ok, so not yet. I will approach my binder first I guess

**Comment by magland** [comment]
The same TimeseriesView widget runs in jupyter as well. Just replace
ev.init_colab() by ev.init_jupyter()
